config/routes.rb
Wallet::Application.routes.draw do
  devise_for :users do
    get "/login", to: "devise/sessions#new", as: :login
    get "/register", to: "devise/registrations#new", as: :register 
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end
  get "/profile", to: "users#show", as: :profile

  get "/withdraw", to: "transactions#withdraw", as: :withdraw
  get "/deposit", to: "transactions#deposit", as: :deposit
  get "/transfer", to: "transactions#transfer", as: :transfer



  resources :accounts, only: [:new, :create, :show]
  resources :transactions, only: [:new, :create]

  root 'application#index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :accounts
  has_many :transactions
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user if current_user
      @user = User.find(params[:id]) unless current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="hero-unit">
	<p id="notice"><%= notice %></p>

	<% if !current_user.accounts.blank? %>
		<table class="table table-striped" data-provides="rowlink">
			<caption>Accounts</caption>
			<thead>
		    <tr>
		      <th>Account Number</th>
		      <th>Account Type</th>
					<th>Balance</th>
		    </tr>
		  </thead>
			<tbody>
				<% for account in current_user.accounts do %>
		    <tr>
					<td><%= account.id %><%= link_to "", account_path(account.id) %></td>
					<td><%= account.account_type == 1 ? "Checking" : "Saving" %></td>
					<td>$<%= account.balance %></td>
				</tr>
				<% end %>
		  </tbody>
		</table>
	<% else %>
		<p>No accounts</p>
	<% end %>
	<p><%= link_to "Click here", new_account_path %> to open a new account.</p>

</div>