config/routes.rb
Wallet::Application.routes.draw do
  devise_for :users do
    get "/login", to: "devise/sessions#new", as: :login
    get "/register", to: "devise/registrations#new", as: :register 
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end
  get "/profile", to: "users#show", as: :profile

  get "/withdraw", to: "transactions#withdraw", as: :withdraw
  get "/deposit", to: "transactions#deposit", as: :deposit
  get "/transfer", to: "transactions#transfer", as: :transfer



  resources :accounts, only: [:new, :create, :show]
  resources :transactions, only: [:new, :create]

  root 'application#index'
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :new_transaction, only: [:new, :deposit, :withdraw, :transfer]
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      
      response = ""
      if @transaction.transaction_type == 1
        response = 1
      elsif @transaction.transaction_type == 2
        response = 2
      elsif @transaction.transaction_type == 3 and @transaction.source_account_id == current_user.id
        response = 3
      else
        response = 4
      end
      
      if @transaction.save
        format.json { render action: 'show', status: :created, location: @transaction }
        if response == 1
          format.html { redirect_to account_path(@transaction.source_account_id), notice: 'Withdrawl completed.' }
        elsif response == 2
          format.html { redirect_to account_path(@transaction.destination_account_id), notice: 'Deposit completed.' }
        elsif response == 3
          format.html { redirect_to account_path(@transaction.source_account_id), notice: 'Transfer complete.' }
        else
          format.html { redirect_to account_path(@transaction.destination_account_id), notice: 'Transfer completed.' }
        end
      else
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
        if response == 1
          format.html { render action: 'withdraw' }
        elsif response == 2
          format.html { render action: 'deposit' }
        else
          format.html { render action: 'transfer' }
        end
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  def withdraw
  end
  
  def deposit    
  end
  
  def transfer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
    
    def new_transaction
      @transaction = Transaction.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params[:transaction].permit(:user_id, :source_account_id, :destination_account_id, :transaction_type, :destination_balance, :source_balance, :amount)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/deposit.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@transaction.errors.count, "error") %> occured:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="center hero-unit">
		<%= f.label "Deposit into which account?" %> 
		<%= f.select(:destination_account_id, current_user.accounts.all.collect {|a| [a.account_type == 1 ? "#{a.id} Checking : $#{a.balance}" : "#{a.id} Savings : $#{a.balance}", a.id]}) -%>
	
		<%= f.label "Amount?" %> 
		<div class="input-prepend">
			<span class="add-on">$</span>
			<%= f.number_field(:amount, min: 0, step: 0.01) %> 
		</div>
	</div>

  <div class="actions">
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :transaction_type, value: 2 %>
    <%= f.submit "Make Deposit" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/transfer.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@transaction.errors.count, "error") %> occured:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="center hero-unit">
		<%= f.label "Transfer from which account?" %> 
		<%= f.select(:source_account_id, current_user.accounts.all.collect {|a| [a.account_type == 1 ? "#{a.id} Checking : $#{a.balance}" : "#{a.id} Savings : $#{a.balance}", a.id]}) -%>
	
		<%= f.label "Account number to deposit into:" %>
		<%= f.number_field(:destination_account_id, min: 0, step: 1) %>
		
		<%= f.label "Amount?" %> 
		<div class="input-prepend">
			<span class="add-on">$</span>
			<%= f.number_field(:amount, min: 0, step: 0.01) %> 
		</div>
	</div>
	


  <div class="actions">
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :transaction_type, value: 3 %>
    <%= f.submit "Transfer funds" %>
  </div>
<% end %>

app/views/transactions/withdraw.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@transaction.errors.count, "error") %> occured:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="center hero-unit">
		<%= f.label "Withdraw from which account?" %> 
		<%= f.select(:source_account_id, current_user.accounts.all.collect {|a| [a.account_type == 1 ? "#{a.id} Checking : $#{a.balance}" : "#{a.id} Savings : $#{a.balance}", a.id]}) -%>
	
		<%= f.label "Amount?" %> 
		<div class="input-prepend">
			<span class="add-on">$</span>
			<%= f.number_field(:amount, min: 0, step: 0.01) %> 
		</div>
	</div>

  <div class="actions">
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :transaction_type, value: 1 %>
    <%= f.submit "Make Withdrawl" %>
  </div>
<% end %>