config/routes.rb
Wallet::Application.routes.draw do
  devise_for :users do
    get "/login", to: "devise/sessions#new", as: :login
    get "/register", to: "devise/registrations#new", as: :register 
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end
  get "/profile", to: "users#show", as: :profile

  get "/withdraw", to: "transactions#withdraw", as: :withdraw
  get "/deposit", to: "transactions#deposit", as: :deposit
  get "/transfer", to: "transactions#transfer", as: :transfer



  resources :accounts, only: [:new, :create, :show]
  resources :transactions, only: [:new, :create]

  root 'application#index'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wallet" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
					<%= link_to "Wallet", root_path, class: "brand" %>
          <div class="container nav-collapse">
						<% if user_signed_in? %>
            <ul class="nav">
              <li><%= link_to current_user.username, profile_path, 'data-no-turbolink' => true  %></li>
							<li><%= link_to "Logout", logout_path %></li>
            </ul>
						<% else %>
            <ul class="nav">
              <li><%= link_to "Login", login_path  %></li>
							<li><%= link_to "Sign up", register_path %></li>
            </ul>
						<% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span8">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
					
					<% if user_signed_in? %>
          <div class="span4" style="margin-top: 41px;">
            <div class="well sidebar-nav">
              <h3>Manage your accounts</h3>
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <li><%= link_to "View your Accounts", profile_path, 'data-no-turbolink' => true %></li>
                <li><%= link_to "Make a Withdrawl", withdraw_path  %></li>
                <li><%= link_to "Make a Deposit", deposit_path  %></li>
                <li><%= link_to "Transfer Funds", transfer_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
					<% end %>
        </div><!--/row-->

      <footer>
        <p>&copy; Joey Hoang 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>