config/routes.rb
Wallet::Application.routes.draw do
  devise_for :users do
    get "/login", to: "devise/sessions#new", as: :login
    get "/register", to: "devise/registrations#new", as: :register 
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end
  get "/profile", to: "users#show", as: :profile

  get "/withdraw", to: "transactions#withdraw", as: :withdraw
  get "/deposit", to: "transactions#deposit", as: :deposit
  get "/transfer", to: "transactions#transfer", as: :transfer



  resources :accounts, only: [:new, :create, :show]
  resources :transactions, only: [:new, :create]

  root 'application#index'
  
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
  has_many :withdrawls, class_name: "Transaction", foreign_key: :destination_account_id
  has_many :deposits, class_name: "Transaction", foreign_key: :source_account_id

  def Account.account_types 
    { "Checking" => 1, "Saving" => 2 }
  end

  def transactions
    (withdrawls + deposits).sort_by { |obj| obj.created_at }
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to profile_path, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to profile_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :account_type)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
  <div>
		<%= f.label :account_type %> 
		<%= f.select(:account_type, [['Checking', 1], ['Saving', 2]]) %>
	</div>

  <div class="actions">
		<%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/new.html.erb
<div class="center hero-unit">
	<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path, 'data-no-turbolink' => true %>
</div>

app/views/accounts/show.html.erb
<div class="hero-unit">

<p id="notice"><%= notice %></p>

<h2>Account Balance: <small>$<%= @account.balance %></small></h2>

<table class="table table-bordered">
	<caption>Transactions</caption>
	<thead>
    <tr>
      <th>Date</th>
      <th>Type</th>
			<th>Debit</th>
			<th>Credit</th>
			<th>Balance</th>
    </tr>
  </thead>
	<tbody>
		<% for transaction in @account.transactions do %>
    <tr>
			<% tt = transaction.transaction_type %>
			<td><abbr title="<%= transaction.created_at.to_s(:db) %> UTC"><%= transaction.created_at.strftime("%b/%d/%Y") %></abbr></td>
			<% if transaction.transaction_type == 1 %>
				<td>Withdrawl</td>
			<% elsif transaction.transaction_type == 2 %>
				<td>Deposit</td>
			<% else %>
				<td>Transfer</td>
			<% end %>
			<td>
				<% if tt == 1 or (tt == 3 and transaction.source_account_id == @account.id) %>
					$<%= transaction.amount %>
				<% end %></td>
			<td>
				<% if tt == 2 or (tt == 3 and transaction.destination_account_id == @account.id) %>
					$<%= transaction.amount %>
				<% end %>
			</td>
			<% if tt == 1 or (tt == 3 and transaction.source_account_id == @account.id) %>
				<td>$<%= transaction.source_balance %></td>
			<% else %>
				<td>$<%= transaction.destination_balance %></td>
			<% end %>
		</tr>
		<% end %>
  </tbody>
</table>

<br/>

<%= link_to 'Back', profile_path, 'data-no-turbolink' => true %>

</div>